name: AcidIsland
main: com.wasteofplastic.acidisland.AcidIsland
version: 1.2
description: Acid Island
author: Tastybento
depend: [Vault]
loadbefore: [Multiverse-Core]
commands:
    ai:
        description: Main player command
        aliases: [is, island, ai]
        usage:  |
             /island help
    acid:
        description: Admin commands
        usage:  |
            /acid
    aic:
        description: Game challenges
        aliases: [c, challenge, aic, aichallenge, challenges]
        usage:  |  
            /challenge
permissions:    
  acidisland.*:
    children:
      acidisland.island.*:
        children:
          acidisland.island.create:
            description: Let the player use the /island command
            default: true
          acidisland.island.info:
            description: Let the player check their island level
            default: true
          acidisland.island.topten:
            description: Let the player see the top ten list
            default: true
          acidisland.island.sethome:
            description: Let the player set their island teleport point
            default: true
          acidisland.island.challenges:
            description: Let the player use the /challenges command
            default: true
          acidisland.island.warp:
            description: Let the player use /island warp to warp to a players island
            default: true
          acidisland.island.addwarp:
            description: Let the player place a Welcome warp sign
            default: true
          acidisland.island.minishop:
            description: Allows usage of the minishop
            default: true
          acidisland.island.controlpanel:
            description: Allows usage of the island GUI
            default: true
      acidisland.team.*:
        children:
          acidisland.team.create:
            description: Let a player invite other players to join a team
            default: true
          acidisland.team.kick:
            description: Let a player kick other players
            default: true
          acidisland.team.makeleader:
            description: Let a player make another player leader of the team
            default: true
          acidisland.team.join:
            description: Let a player join another player's team
            default: true
          acidisland.team.vip:
            description: Allows a bigger team size
            default: false
          acidisland.team.vip2:
            description: Allows a bigger team size
            default: false
      acidisland.craft.*:
        children:
          acidisland.craft.enderchest:
            description: Allow crafting and use of enderchests in AcidIsland
            default: false
      acidisland.mod.*:
        children:
          acidisland.mod.topten:
            description: Let a moderator update the top ten list
            default: op
          acidisland.mod.info:
            description: Let a moderator see info on a player
            default: op
          acidisland.mod.challenges:
            description: Let a moderator access challenge commands 
            default: op
          acidisland.mod.noburn:
            description: Gives mod immunity to acid
            default: false
          acidisland.mod.clearreset:
            description: Allow clearing of island reset limit
            default: false
          acidisland.mod.tp:
            description: Allows teleporting to a players island
            default: false
          acidisland.mod.bypassprotect:
            description: Bypasses island protection
            default: false
      acidisland.admin.*:
        children:
          acidisland.admin.reload:
            description: Reload the config.yml
            default: op
          acidisland.admin.delete:
            description: Let a player completely remove a player's island (including blocks)
            default: op
          acidisland.admin.register:
            description: Let a player register the nearest island (using the bedrock) to another player.
            default: op
          acidisland.admin.purge:
            description: Let a player purge old islands.
            default: op
          acidisland.admin.noburn:
            description: Gives admin immunity to acid
            default: false
          acidisland.admin.setspawn:
            description: Allows use of spawn tools
            default: op
